version: '3.4'
services:
    service.registry:
        build: 
            context: ./service.registry
        ports:
            - 8000:80
        command: ["/app"]

    service.hive:
        build:
            context: ./service.hive
            target: dev
        ports:
            - 8080:8080

    service.shelly:
        build:
            context: ./service.shelly
        ports:
            - 9000:80
        command: ["/app"]

    service.hue:
        build:
            context: ./service.hue
        ports:
            - 9001:80
        command: ["/app"]

