version: '3'
services:
    service.registry:
        build: 
            context: ./service.registry
        volumes:
            - "./service.registry:/usr/src/app"
        ports:
            - 8000:80
        command: ["app"]

    service.shelly:
        build:
            context: ./service.shelly
        volumes:
            - "./service.shelly:/usr/src/app"
        ports:
            - 9000:80
        command: ["app"]
