version: '3.4'
services:
    service.registry:
        build: 
            context: ./service.registry
        ports:
            - 8000:80
        command: ["/app"]

    service.hive:
        build:
            context: ./service.hive
            target: prod
        ports:
            - 8080:80

    service.shelly:
        build:
            context: ./service.shelly
        ports:
            - 9000:80
        command: /app -p 80 -u ${MQTTUSER} -pw ${MQTTPASSWD} -h ${MQTTHOST}

    service.hue:
        build:
            context: ./service.hue
        ports:
            - 9001:80
        command: /app -p 80 -ha ${BRIDGEADDRESS} -ht ${BRIDGETOKEN}
